Update to commit 8efd4a1 from git@github.com:x-team/wp-settings-revisions.git
Includes the following commit(s):

commit 8efd4a1a3a505e4abff1cebd02edee27c313ed6b
Author: Weston Ruter <weston@x-team.com>

    Set exact casing of X-Team username

M	php/readme-parser.php
M	readme.txt


git-svn-id: https://plugins.svn.wordpress.org/settings-revisions/trunk@735825 b8457f37-d9ea-0310-8a92-e5e31aec5664

diff --git a/bin/svn-push b/bin/svn-push
--- a/bin/svn-push
+++ b/bin/svn-push
@@ -4,11 +4,11 @@ set -e
 
 cd $(dirname $0)/..
 
-#if [ -n "$(git status -s -uno)" ]; then
-#	git status
-#	echo "Error: Git state has modified or staged files. Commit or reset." >&2
-#	exit 1
-#fi
+if [ -n "$(git status -s -uno)" ]; then
+	git status
+	echo "Error: Git state has modified or staged files. Commit or reset." >&2
+	exit 1
+fi
 
 git_root=$(pwd)
 
@@ -66,6 +66,6 @@ fi
 
 cd $svn_repo_dir
 
-#svn commit -F $svn_commit_file
+svn commit -F $svn_commit_file
 
-#rm $svn_commit_file
+rm $svn_commit_file
