Update to commit 5a968d5 from git@github.com:x-team/wp-settings-revisions.git
Includes the following commit(s):

commit 5a968d5d9aedd2cc6b289111276c3a373116bf90
Author: Weston Ruter <weston@x-team.com>

    Skip creating tag if already exists

M	bin/svn-push

commit 5bf6c4b63fb62b64b12f319e20f9cef789893089
Author: Weston Ruter <weston@x-team.com>

    Add -f to svn-push

M	bin/svn-push

commit dd0aab03951204f6ef34d38da0c1aad27e946a97
Author: Weston Ruter <weston@x-team.com>

    Update markdown readme

M	readme.md

commit 60bd783e6e9cf65e8216224af01d297475a89e66
Author: Weston Ruter <weston@x-team.com>

    Update readme for 0.1.3 release

M	readme.txt

commit 880415748ddaa2c3b974df4f010d75b296aec7b2
Author: Weston Ruter <weston@x-team.com>

    Maybe unserialize get_post_custom() arrays

M	php/post-type.php

commit 64e707c35f1c668130907b5725dac0679744c1d8
Author: Weston Ruter <weston@x-team.com>

    Use customize_controls_enqueue_scripts action

M	php/meta-control.php
M	settings-revisions.php

commit 561b05f8252e330e5b211de371c19c6a4fe6a250
Author: Weston Ruter <weston@x-team.com>

    Update svn-push script

M	bin/svn-push
A	svn-url


git-svn-id: https://plugins.svn.wordpress.org/settings-revisions/trunk@768172 b8457f37-d9ea-0310-8a92-e5e31aec5664

diff --git a/bin/svn-push b/bin/svn-push
--- a/bin/svn-push
+++ b/bin/svn-push
@@ -1,12 +1,29 @@
 #!/bin/bash
+# Given a svn-url file one directory up, export the latest git commits to the specified SVN repo.
+# Create a git release tag from the verison specified in the plugin file.
+# Author: Weston Ruter (@westonruter)
 
 set -e
 
 cd $(dirname $0)/..
 
-if [ -n "$(git status -s -uno)" ]; then
+if [ ! -e svn-url ]; then
+	echo "Error: Missing svn-url file" >&2
+	exit 1
+fi
+
+force=
+while getopts 'f' option; do
+	case $option in
+		f)
+			force=1
+			;;
+	esac
+done
+
+if [ -n "$(git status -s -uno)" ] && [ -z "$force" ]; then
 	git status
-	echo "Error: Git state has modified or staged files. Commit or reset." >&2
+	echo "Error: Git state has modified or staged files. Commit or reset, or supply -f" >&2
 	exit 1
 fi
 
@@ -16,9 +33,50 @@ current_branch=$(git rev-parse --abbrev-ref HEAD)
 if [ $current_branch != 'master' ]; then
 	git checkout master
 fi
-git pull
-svn_url=https://plugins.svn.wordpress.org/settings-revisions/
+
+bin/generate-markdown-readme
+git add readme.md
+if [ -n "$(git status --porcelain readme.md)" ]; then
+	echo "Please commit (--amend?) the updated readme.md"
+	exit 1
+fi
+
+git pull origin master
+git push origin master
+svn_url=$(cat svn-url)
 svn_repo_dir=$git_root/svn
+
+for php in *.php; do
+	if grep -q 'Plugin Name:' $php && grep -q 'Version:' $php; then
+		plugin_version=$(cat $php | grep 'Version:' | sed 's/.*Version: *//')
+	fi
+done
+
+if [ -z "$plugin_version" ]; then
+	echo "Unable to find plugin version"
+	exit 1
+fi
+
+if ! grep -q "$plugin_version" readme.txt; then
+	echo "Please update readme.txt to include $plugin_version in changelog"
+	exit 1
+fi
+
+git show-ref --tags --quiet --verify -- "refs/tags/$plugin_version"
+has_tag=$?
+
+if [ $has_tag == 0 ] && [ -z "$force" ]; then
+	echo "Plugin version $plugin_version already tagged. Please bump version and try again, or supply -f"
+	exit 1
+fi
+
+if [ $has_tag != 0 ]; then
+	echo "Tagging plugin version $plugin_version"
+	git tag "$plugin_version" master
+	git push origin "$plugin_version"
+else
+	echo "Skipping plugin tag $plugin_version since already exists"
+fi
 
 if [ ! -e $svn_repo_dir ]; then
 	svn checkout $svn_url $svn_repo_dir
@@ -39,8 +97,10 @@ cat <(
 ) | sort | rsync -avz --delete --delete-excluded --include-from=- --exclude='*' $git_root/ ./
 
 # move assets directory to proper location in SVN
-rsync -avz --delete ./assets/ ../assets/
-rm -r ./assets/
+if [ -d assets ]; then
+	rsync -avz --delete ./assets/ ../assets/
+	rm -r ./assets/
+fi
 
 # convert .gitignores to svn:ignore
 for gitignore in $(find . -name .gitignore); do
@@ -55,7 +115,9 @@ cd $svn_repo_dir
 svn status . | grep "^\!" | sed 's/^\! *//g' | xargs svn rm
 
 # Add everything left to commit
-svn add --force assets
+if [ -d assets ]; then
+	svn add --force assets
+fi
 svn add --force trunk
 
 # Do SVN commit
